apiVersion: v1
kind: Service
metadata:
  name: result-service
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 80
      nodePort: 31322
  selector:
      name: result-app-pod
      app: demo-voting-app
      
