apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    name: voting-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: voting-application
      image: dockersamples/examplevotingapp_vote
      ports:
        - containerPort: 80
          name: voting-app-pod
  